"""Offer-aware lead scoring.

Replaces the hardcoded "no website = A, bad website = B, good website = C"
logic that only made sense when the offer was 'we build websites'.

A scoring rubric (`configs/scoring_rubric.json`) is generated by
`config_generator.py` based on the user's actual offer, and can be hand-edited
afterwards. The rubric is a list of tiers evaluated top-to-bottom; the first
tier whose signals all pass becomes the lead's priority.

This module exposes ONE public function:

    score_lead(biz, website_data=None, rubric=None) -> dict

Returning {"priority", "tier_label", "matched_signals", "tier_index"}.

A tier looks like:

  {
    "priority": "A",
    "label": "Hot — perfect fit, no current solution",
    "signals": {
      "name_contains_any":     ["hotel", "resort"],
      "name_contains_none":    ["budget", "hostel"],
      "place_types_any":       ["lodging"],
      "website_required":      false,        # null=any, true=must have, false=must NOT have
      "website_score_min":     null,
      "website_score_max":     null,
      "website_contains_any":  ["wellness"],
      "website_contains_none": ["sauna", "klafs"],
      "min_review_count":      0
    }
  }

Empty / missing signals are skipped (always pass). An empty `signals` block
makes the tier a catch-all — useful as the final "C" bucket.
"""
import json
from pathlib import Path
from typing import Any, Optional

ROOT = Path(__file__).resolve().parent.parent
RUBRIC_FILE = ROOT / "configs" / "scoring_rubric.json"
RUBRIC_EXAMPLE = ROOT / "configs" / "scoring_rubric.json.example"

# Built-in fallback used when no rubric file exists yet (e.g. fresh install
# before config_generator has run, or user deleted the file).
# Mirrors the legacy trade-business behavior so existing flows keep working.
_LEGACY_RUBRIC: dict = {
    "offer": "(legacy default — generated when no scoring_rubric.json was found)",
    "instructions": "This is the auto-generated trade-business default. Run `python3 scripts/config_generator.py <country> \"<your offer>\"` to replace it with one tailored to your actual offer.",
    "tiers": [
        {
            "priority": "A",
            "label": "Hot — no website (easiest pitch)",
            "signals": {
                "website_required": False,
                "min_review_count": 5,
            },
        },
        {
            "priority": "B",
            "label": "Warm — bad website",
            "signals": {
                "website_required": True,
                "website_score_max": 60,
            },
        },
        {
            "priority": "C",
            "label": "Cold — decent website",
            "signals": {},
        },
    ],
}


def load_rubric(path: Optional[Path] = None) -> dict:
    """Load the rubric file, falling back to the built-in legacy default."""
    p = path or RUBRIC_FILE
    if p.exists():
        try:
            data = json.loads(p.read_text())
            if isinstance(data, dict) and "tiers" in data:
                return data
        except Exception:
            pass
    return _LEGACY_RUBRIC


def _norm(text: Any) -> str:
    return (text or "").lower() if isinstance(text, str) else ""


def _matches_tier(biz: dict, website_data: dict, signals: dict) -> tuple[bool, list[str]]:
    """Returns (does_match, matched_signal_descriptions)."""
    if not signals:
        return True, ["catch-all (empty signals)"]

    matched: list[str] = []
    name = _norm(biz.get("name") or biz.get("business_name", ""))
    address = _norm(biz.get("address", ""))
    place_types = [_norm(t) for t in biz.get("types", [])]
    review_count = int(biz.get("review_count", 0) or 0)

    has_site = bool(website_data.get("has_website")) if website_data else bool(biz.get("website"))
    site_score = int((website_data or {}).get("score", biz.get("website_score") or 0) or 0)
    site_text = _norm((website_data or {}).get("raw_html") or biz.get("website_text", ""))

    # name_contains_any — at least one term must appear in name OR address
    needles = signals.get("name_contains_any") or []
    if needles:
        hit = next((n for n in needles if _norm(n) and _norm(n) in name + " " + address), None)
        if not hit:
            return False, []
        matched.append(f"name has '{hit}'")

    # name_contains_none — none of these may appear
    blockers = signals.get("name_contains_none") or []
    if blockers:
        hit = next((b for b in blockers if _norm(b) and _norm(b) in name + " " + address), None)
        if hit:
            return False, []
        matched.append("name clean of blockers")

    # place_types_any
    types_needed = signals.get("place_types_any") or []
    if types_needed:
        hit = next((t for t in types_needed if _norm(t) in place_types), None)
        if not hit:
            return False, []
        matched.append(f"place_type='{hit}'")

    # website_required — None/missing = don't care
    site_req = signals.get("website_required")
    if site_req is True and not has_site:
        return False, []
    if site_req is False and has_site:
        return False, []
    if site_req is True:
        matched.append("has website")
    if site_req is False:
        matched.append("no website")

    # website_score thresholds (only meaningful when there IS a website)
    if has_site:
        smin = signals.get("website_score_min")
        smax = signals.get("website_score_max")
        if smin is not None and site_score < int(smin):
            return False, []
        if smax is not None and site_score > int(smax):
            return False, []
        if smin is not None or smax is not None:
            matched.append(f"website_score={site_score}")

    # website content keywords (only checked if we actually have site_text)
    if site_text:
        wany = signals.get("website_contains_any") or []
        if wany:
            hit = next((w for w in wany if _norm(w) and _norm(w) in site_text), None)
            if not hit:
                return False, []
            matched.append(f"site mentions '{hit}'")
        wnone = signals.get("website_contains_none") or []
        if wnone:
            hit = next((w for w in wnone if _norm(w) and _norm(w) in site_text), None)
            if hit:
                return False, []
            matched.append("site free of disqualifiers")

    # min_review_count
    rmin = signals.get("min_review_count")
    if rmin is not None and review_count < int(rmin):
        return False, []
    if rmin is not None and rmin > 0:
        matched.append(f"reviews={review_count}")

    return True, matched


def score_lead(biz: dict, website_data: Optional[dict] = None, rubric: Optional[dict] = None) -> dict:
    """Return {"priority", "tier_label", "matched_signals", "tier_index"}.

    The lead's priority is the FIRST tier whose signals all pass.
    If no tier matches (shouldn't happen if the rubric ends with a catch-all),
    falls back to the rubric's last tier so we always return something.
    """
    rubric = rubric or load_rubric()
    website_data = website_data or {}
    tiers = rubric.get("tiers", [])

    for idx, tier in enumerate(tiers):
        ok, matched = _matches_tier(biz, website_data, tier.get("signals") or {})
        if ok:
            return {
                "priority": tier.get("priority", "C"),
                "tier_label": tier.get("label", ""),
                "matched_signals": matched,
                "tier_index": idx,
            }

    # No tier matched — fall back to the rubric's last tier as a catch-all,
    # or to "C" / blank if the rubric is empty.
    if tiers:
        last = tiers[-1]
        return {
            "priority": last.get("priority", "C"),
            "tier_label": last.get("label", "") + " (no other tier matched)",
            "matched_signals": [],
            "tier_index": len(tiers) - 1,
        }
    return {"priority": "C", "tier_label": "fallback (no rubric loaded)", "matched_signals": [], "tier_index": -1}
